# Generated by Django 2.0.6 on 2020-06-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permission', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='ismenu',
            field=models.BooleanField(default=True, verbose_name='是否是菜单'),
        ),
        migrations.AddField(
            model_name='permission',
            name='parentid',
            field=models.CharField(default=1, max_length=32, verbose_name='父菜单id'),
            preserve_default=False,
        ),
    ]
