# Generated by Django 3.0.6 on 2020-06-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('fenlei', models.CharField(max_length=20)),
                ('neirong', models.CharField(max_length=20000)),
            ],
            options={
                'db_table': 't_context',
            },
        ),
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='static/img')),
            ],
            options={
                'db_table': 't_pic',
            },
        ),
    ]
