# Generated by Django 3.0.6 on 2020-06-02 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='pic',
            table=None,
        ),
    ]
