# Generated by Django 2.0.6 on 2020-06-05 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('context', '0002_auto_20200602_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='context',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pic',
            name='img',
            field=models.ImageField(upload_to='static/img/up_pic'),
        ),
    ]
