# Generated by Django 2.0.6 on 2020-06-06 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='zhangjie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zhangjie_name', models.CharField(max_length=20)),
                ('zhangjie_size', models.CharField(max_length=20)),
                ('zhangjie_time', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='zhuanjis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15)),
                ('score', models.CharField(max_length=15)),
                ('author', models.CharField(max_length=15)),
                ('boyin', models.CharField(max_length=15)),
                ('zhangjieshu', models.CharField(max_length=15)),
                ('jianjie', models.CharField(max_length=150)),
                ('statue', models.BooleanField(default=True)),
                ('pic', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='zhangjie',
            name='zj_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zhuanji.zhuanjis'),
        ),
    ]
