# Generated by Django 2.0.6 on 2020-05-30 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='lunbo_picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(max_length=500)),
                ('date', models.CharField(max_length=500)),
                ('status', models.BooleanField(default=True)),
                ('pic', models.ImageField(upload_to='static/img')),
            ],
        ),
    ]
